MvcApplication1/Models/CalculoIR.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MvcApplication1.Models
{
    public class CalculoIR
    {
        private decimal salarioAnual;
        public CalculoIR(decimal salarioAnual)
        {
            this.salarioAnual = salarioAnual;
        }

        public decimal Calcular()
        {
            if (salarioAnual <= 1499.15m)
                return 0;
            if (salarioAnual <= 2246.75m)
                return salarioAnual * 0.075m - 112.43m;
            if (salarioAnual <= 2995.7m)
                return salarioAnual * 0.15m - 280.94m;
            if (salarioAnual <= 3743.19m)
                return salarioAnual * 0.225m - 505.62m;
            return salarioAnual * 0.275m - 692.78m;

        }
    }
}

MvcApplication1/Controllers/IRController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public class IRController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Calculo(decimal salario)
        {
            ViewBag.Salario = salario;
            ViewBag.IR = new CalculoIR(salario).Calcular();
            return View("Index");
        }

    }
}

MvcApplication1/Views/IR/Index.cshtml
<h2>Cálculo IR</h2>
@using (Html.BeginForm("Calculo", "IR"))
{
    <div>
        @Html.TextBox("Salario")<br />
        <input type="submit" name="Calcule" />
        @if (ViewBag.IR != null){
            <p>
                O valor é <span id="Resultado">@ViewBag.IR.ToString("f")</span>.
            </p>
        }
    </div>
}

MvcApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    @RenderBody()
</body>
</html>